# Configuracao do DataSource (Supabase Pooler IPv4)
spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.hvuprzgcxkirpgftnohx
spring.datasource.password=Kongkxd12344321!
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracao JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true